name: ${project.name}
main: net.daboross.bukkitdev.subcommandexample.SubCommandExamplePlugin
version: ${project.version}
author: Dabo Ross
description: Example of SubCommands using CommandExecutorBase
